# Generated by Django 2.2 on 2019-07-29 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mysqlinfo',
            unique_together={('ip', 'hostname', 'port', 'db_name', 'role')},
        ),
    ]
