# Generated by Django 2.2 on 2019-07-29 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20190729_0301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatabaseInfo',
            new_name='InstanceInfo',
        ),
    ]
