# Generated by Django 2.2 on 2019-07-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20190729_0527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MysqlInitInfo',
        ),
        migrations.AddField(
            model_name='instanceinfo',
            name='hostname',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instanceinfo',
            name='role',
            field=models.CharField(default='0.0.0.0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instanceinfo',
            name='version',
            field=models.CharField(default='1.1.1.1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mysqlinfo',
            name='master_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
