# Generated by Django 2.2 on 2019-07-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20190730_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='asset_obj',
        ),
        migrations.AddField(
            model_name='errorlog',
            name='obj',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
