# Generated by Django 2.2 on 2019-07-30 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20190730_0133'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mysqlinfo',
            unique_together={('hostname',)},
        ),
    ]
