# Generated by Django 2.2 on 2019-07-30 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_auto_20190730_0203'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mysqlinfo',
            unique_together={('hostname', 'ip', 'port', 'db_name', 'role')},
        ),
    ]
