# Generated by Django 2.2 on 2019-07-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20190730_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysqlinfo',
            name='archive_ip',
        ),
    ]
