# Generated by Django 2.2 on 2019-07-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_auto_20190730_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupinfo',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
