# Generated by Django 2.2 on 2019-07-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_backupinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupinfo',
            name='backup_file',
            field=models.CharField(default='', max_length=128),
        ),
    ]
