# Generated by Django 2.2 on 2019-07-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_backupinfo_backup_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupinfo',
            name='backup_file',
        ),
    ]
