# Generated by Django 2.2 on 2019-07-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_auto_20190730_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupinfo',
            name='backup_time',
            field=models.DateTimeField(),
        ),
    ]
