# Generated by Django 2.2 on 2019-07-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0018_auto_20190731_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupinfo',
            name='backup_time',
            field=models.CharField(max_length=32),
        ),
    ]
