# Generated by Django 2.2 on 2019-08-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0020_auto_20190731_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbgranthistory',
            name='judge_time',
            field=models.DateTimeField(),
        ),
    ]
