# Generated by Django 2.2 on 2019-08-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0022_auto_20190801_1013'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dbgranthistory',
            unique_together={('db_ip', 'db_username', 'port', 'db_name', 'host_ip')},
        ),
    ]
