# Generated by Django 2.2 on 2019-08-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0023_auto_20190801_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysqlinfo',
            name='root_pass',
        ),
    ]
